blogApp/Controllers/BlogPostController.cs
using blogApp.Data;
using blogApp.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace blogApp.Controllers
{
    public class BlogPostController : Controller
    {
        private readonly AppDbContext _context;

        public BlogPostController(AppDbContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            var blogPosts = _context.Blog.ToList();

            return View(blogPosts);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(Blog blog)
        {
            if (ModelState.IsValid)
            {
                blog.CreatedAt = DateTime.Now;
                _context.Add(blog);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            return View(blog);
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var blogPost = await _context.Blog.FindAsync(id);
            if (blogPost == null)
            {
                return NotFound();
            }
            return View(blogPost);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Blog blog)
        {
            if (id != blog.id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                _context.Update(blog);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(blog);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var blogPost = await _context.Blog.FindAsync(id);
            if (blogPost == null)
            {
                return NotFound();
            }

            return View(blogPost);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var blogPost = await _context.Blog.FindAsync(id);

            if (blogPost == null)
            {
                return NotFound();
            }
            _context.Blog.Remove(blogPost);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        //[HttpPost]
        //public async Task<IActionResult> AddComment(int id, string Text)
        //{
        //    if (!string.IsNullOrEmpty(Text))
        //    {
        //        var blog = await _context.Blog.Include(b => b.Comments).FirstOrDefaultAsync(b => b.id == id);
        //        if (blog != null)
        //        {
        //            var comment = new Comment
        //            {
        //                Text = Text,
        //                CreatedAt = DateTime.Now,
        //                AuthorEmail = User?.Identity?.Name ?? ""
        //            };
        //            blog.Comments.Add(comment);
        //            await _context.SaveChangesAsync();
        //        }
        //    }

        //    return RedirectToAction("CreateComment", new { id = id });
        //}
    }
}

blogApp/Views/BlogPost/Create.cshtml
@model blogApp.Models.Blog


@{
    ViewData["Title"] = "Add new post!";
}


<div class="form-container sign-in-container" style="margin-left: 25%; padding: 70px 0">
    <h1>Create Blog Post</h1>
    <form asp-action="Create">
        <div class="form-group">
            <label asp-for="Title" class="control-label"></label>
            <input asp-for="Title" class="form-control" />
            <span asp-validation-for="Title" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="Content" class="control-label"></label>
            <textarea asp-for="Content" class="form-control" style="width: 240px; height: 50px"></textarea>
            <span asp-validation-for="Content" class="text-danger"></span>
        </div>
        <div class="form-group">
            <input type="submit" value="Create" class="btn btn-primary" />
        </div>
    </form>
</div>

blogApp/Views/BlogPost/CreateComment.cshtml
@* @model blogApp.Models.Blog

@{
    ViewData["Title"] = Model.Title;
}
<div class="form-container sign-in-container" style="margin-left: 25%; padding: 70px 0">


<h1>@Model.Title</h1>
<p>@Model.Content</p>

<hr />

<h3>Comments</h3>

<ul>
    @if(Model.Comments.Count() > 0)
    {
       @foreach (var comment in Model.Comments)
        {
            <li>
                <strong>@comment.CreatedAt.ToString("g")</strong> - @comment.Text
            </li>
        }
    }  
</ul>

<hr />
    <h4>Add a comment</h4>

    <form asp-action="AddComment" method="post">
        <input type="hidden" asp-for="id" />
        <div class="form-group">
            <textarea name="Text" class="form-control" placeholder="Write your comment here..."></textarea>
        </div>
        <div class="form-group">
            <input type="submit" value="Add Comment" class="btn btn-primary" />
        </div>
    </form>

</div>



 *@

blogApp/Views/BlogPost/Delete.cshtml
@model blogApp.Models.Blog
@{
    ViewData["Title"] = "Delete Blog Post";
}


<div class="form-container sign-in-container" style="margin-left: 25%; padding: 20px 0">

    <h1 style="margin: 30px">Delete Blog Post</h1>

    <h3 style="color: #3c97bf;">Are you sure you want to delete this?</h3>

    <div>
        <h3 style="color: #222;">@Model.Title</h3>
        <div>
            <p>@Model.Content</p>
        </div>
    </div>

    <form asp-action="Delete" style="height: 50%">
        <input type="hidden" asp-for="id" />
        <input type="submit" value="Delete" class="btn btn-danger" style="background-color: #ff4b2b" />
        <a asp-action="Index" class="btn btn-secondary">Cancel</a>
    </form>

</div>

blogApp/Views/BlogPost/Edit.cshtml
@model blogApp.Models.Blog
   

@{
    ViewData["Title"] = "Edit Blog Post";
}


<div class="form-container sign-in-container" style="margin-left: 25%; padding: 70px 0">
    <h1>Edit Blog Post</h1>

    <form asp-action="Edit">
        <input type="hidden" asp-for="id" />
        <div class="form-group">
            <label asp-for="Title" class="control-label"></label>
            <input asp-for="Title" class="form-control" />
            <span asp-validation-for="Title" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="Content" class="control-label"></label>
            <textarea asp-for="Content" class="form-control" style="width: 240px; height: 50px"></textarea>
            <span asp-validation-for="Content" class="text-danger"></span>
        </div>
        <div class="form-group">
            <input type="submit" value="Save" class="btn btn-primary" />
        </div>
    </form>

</div>

blogApp/Views/BlogPost/Index.cshtml
@model IEnumerable<blogApp.Models.Blog>

@{
    ViewData["Title"] = "Blog Page";
}

<header>
    <nav>
        
        <a href="/Account/RegisterLogin">Home</a>
       
    </nav>
</header>

<h1>Blog Posts</h1>

@if (Model == null || !Model.Any())
{
    <p>No blog posts available. <a href="@Url.Action("Create", "BlogPost")" class="btn btn-primary">Create New</a></p>
}
else
{
    <p>
        <a href="@Url.Action("Create", "BlogPost")" class="btn btn-primary">Create New</a>
    </p>
    <div class="blog_post_container">  
    @foreach( var item in Model)
    {
      <div class="blog_post">
        <div class="img_pod">
            <img src="https://pbs.twimg.com/profile_images/890901007387025408/oztASP4n.jpg" alt="random image">
        </div>
        <div class="container_copy">

                <h3>@Html.DisplayFor(modelItem => item.CreatedAt)</h3>
                <h1>@Html.DisplayFor(modelItem => item.Title)</h1>
                <p>@Html.DisplayFor(modelItem => item.Content)</p>

               
                <a href="@Url.Action("Edit", "BlogPost", new { id = item.id })" class="btn btn-primary">Edit</a>
                <a href="@Url.Action("Delete", "BlogPost", new { id = item.id })" class="btn btn-primary">Delete</a>
        </div>

      </div>
    }
        <div class="pagination">
            <a href="#" id="prev">&laquo;</a>
            <a href="#" class="page-num active" data-page="1">1</a>
            <a href="#" class="page-num" data-page="2">2</a>
            <a href="#" class="page-num" data-page="3">3</a>
            <a href="#" class="page-num" data-page="4">4</a>
            <a href="#" class="page-num" data-page="5">5</a>
            <a href="#" id="next">&raquo;</a>
        </div>

    </div>

    

}

@section Styles {
    <link rel="stylesheet" href="~/css/Index.css" />
}
@section Scripts{
    <script src="~/js/pagination.js"></script>
}